// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDepFdbXqygkk_E7wsF-9fUoNH-4k-_xno',
    appId: '1:307172937314:web:ea979720b6a1b637f3cb3b',
    messagingSenderId: '307172937314',
    projectId: 'cst-whitelabel-app',
    authDomain: 'cst-whitelabel-app.firebaseapp.com',
    storageBucket: 'cst-whitelabel-app.firebasestorage.app',
    measurementId: 'G-5SDBLR04XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3RIOuuze6JJddwqbOWNueQ2-L1NEitc',
    appId: '1:307172937314:android:c0b55c0c5a832235f3cb3b',
    messagingSenderId: '307172937314',
    projectId: 'cst-whitelabel-app',
    storageBucket: 'cst-whitelabel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsO_CwLCgmoChmLkT0Fev0URzuH6whVn8',
    appId: '1:307172937314:ios:cf8dbe93023ab8a4f3cb3b',
    messagingSenderId: '307172937314',
    projectId: 'cst-whitelabel-app',
    storageBucket: 'cst-whitelabel-app.firebasestorage.app',
    iosBundleId: 'com.example.demoCst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsO_CwLCgmoChmLkT0Fev0URzuH6whVn8',
    appId: '1:307172937314:ios:cf8dbe93023ab8a4f3cb3b',
    messagingSenderId: '307172937314',
    projectId: 'cst-whitelabel-app',
    storageBucket: 'cst-whitelabel-app.firebasestorage.app',
    iosBundleId: 'com.example.demoCst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDepFdbXqygkk_E7wsF-9fUoNH-4k-_xno',
    appId: '1:307172937314:web:43ce646c567340e6f3cb3b',
    messagingSenderId: '307172937314',
    projectId: 'cst-whitelabel-app',
    authDomain: 'cst-whitelabel-app.firebaseapp.com',
    storageBucket: 'cst-whitelabel-app.firebasestorage.app',
    measurementId: 'G-5LTND2NYL7',
  );

}