// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwDON3_7Av6B0CiyyszEEpCltveQBjao',
    appId: '1:69645692792:web:e1fae2ab5aa9e0fe8fe28d',
    messagingSenderId: '69645692792',
    projectId: 'cst-abinaya-demo',
    authDomain: 'cst-abinaya-demo.firebaseapp.com',
    storageBucket: 'cst-abinaya-demo.firebasestorage.app',
    measurementId: 'G-3EHQ2Q796H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhJGVok7aOla-PSWuCBe6b6hHVg-bLzvE',
    appId: '1:69645692792:android:d88cf2671fd29b468fe28d',
    messagingSenderId: '69645692792',
    projectId: 'cst-abinaya-demo',
    storageBucket: 'cst-abinaya-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV80QxqQlwYL4rI_xcda9xq14AmJ1xHRQ',
    appId: '1:69645692792:ios:d5ddfd340cec44b28fe28d',
    messagingSenderId: '69645692792',
    projectId: 'cst-abinaya-demo',
    storageBucket: 'cst-abinaya-demo.firebasestorage.app',
    iosBundleId: 'com.example.demoCst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV80QxqQlwYL4rI_xcda9xq14AmJ1xHRQ',
    appId: '1:69645692792:ios:d5ddfd340cec44b28fe28d',
    messagingSenderId: '69645692792',
    projectId: 'cst-abinaya-demo',
    storageBucket: 'cst-abinaya-demo.firebasestorage.app',
    iosBundleId: 'com.example.demoCst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkwDON3_7Av6B0CiyyszEEpCltveQBjao',
    appId: '1:69645692792:web:ea35d03bc529c4ca8fe28d',
    messagingSenderId: '69645692792',
    projectId: 'cst-abinaya-demo',
    authDomain: 'cst-abinaya-demo.firebaseapp.com',
    storageBucket: 'cst-abinaya-demo.firebasestorage.app',
    measurementId: 'G-1V9BTJFP5F',
  );
}
